FORMAT: 1A
HOST: http://api.pinnaclesports.com

# Api documentation

Here you can find any website related resource.

## Headers

`Content-Type: application/json`

`Authorization: {token}`

## Response Codes

<table> 
    <tr> 
        <td>200</td><td nowrap><code>OK</code></td> 
    </tr> 
    <tr> 
        <td>201</td><td nowrap><code>Created</code></td> 
    </tr> 
    <tr> 
        <td>204</td><td nowrap><code>No Content</code></td> 
    </tr>
    <tr> 
        <td>400</td><td nowrap><code>Bad Request</code></td> 
    </tr> 
    <tr> 
        <td>401</td><td nowrap><code>Unauthorized</code></td> 
    </tr>
        <tr> 
        <td>404</td><td nowrap><code>Not found</code></td> 
    </tr>
    <tr> 
        <td>500</td><td nowrap><code>Internal Server Error</code></td> 
    </tr> 
</table> 

#Group Responsible gaming

## Customer's deposit limit [/customers/{customerId}/deposit-limit]

### Retrieve customer's deposit limit [GET]

+ Parameters
    + customerId (string)

+ Request

    + Headers
         
            Content-Type: application/json
            Authorization: {token}  

+ Response 200

    + Body
    
            {
                "PeriodInHours": 672,
                "PeriodInDays": 28,
                "StartDate": "2016-05-19T09:29",
                "CurrentCycleStartDate": "2016-05-19T09:29",
                "Amount": 100,
                "Status": "Active",
                "AddedBy": "cesarc",
                "DateAdded":"2016-05-19T09:29"
            }

+ Response 401

+ Response 404

+ Response 500


### Set customer's deposit limit [PUT]

+ Parameters

    + customerId (string)

+ Request

    + Headers
         
            Content-Type: application/json
            Authorization: {token}  
    + Body
        
            {
                "PeriodInHours": 672,
                "StartDate": "2016-05-19T09:29",
                "Amount": 100,
                "AddedBy": "cesarc"
            }

+ Response 204

+ Response 400 (application/json)

    + Body
            
            {
                "message": "The request is invalid.",
                "errors": 
                    {
                        "request.PeriodInHours": ["A positive number is expected"],
                        "request.StartDate": ["The field is mandatory"],
                        "request.Amount": ["A positive number is expected"],
                        "request.AddedBy": ["The field is mandatory"]
                    }
            }
            
+ Response 401

+ Response 500

### Disable customer's deposit limit [DELETE]

+ Request

    + Headers
         
            Authorization: {token}  


+ Response 204

+ Response 500

## Customer's self-exclusion [/customers/{customerId}/self-exclusion]

### Retrieve customer's self-exclusion [GET]

+ Parameters

    + customerId (string)

+ Request

    + Headers
         
            Content-Type: application/json
            Accept-Language: en-GB
            Authorization: {token}  

+ Response 200

    + Body
    
            {
                "PeriodInHours": 672,
                "PeriodInDays": 28,
                "StartDate": "2016-05-19T09:29",
                "EndDate": "2016-06-16T09:29",
                "Status": "Active",
                "AddedBy": "cesarc",
                "DateAdded":"2016-05-19T09:29"
            }

+ Response 401

+ Response 404 

+ Response 500

### Set customer's self-exclusion [PUT]

+ Request(application/json)

    + Headers
         
            Authorization: {token}  
    + Body
        
            {
                "period": 672
            }

+ Response 204

+ Response 400 (application/json)

    + Body
            
            {
                "message": "The request is invalid.",
                "errors": 
                    {
                        "request.period": ["The provided period is not allowed"]
                    }
            }
            
+ Response 401

+ Response 500

### Disable customer's self-exclusion [DELETE]

+ Request

    + Headers
         
            Authorization: {token}  


+ Response 204

+ Response 500

## Customer's cooling-off period [/customers/{customerId}/cooling-off-period]

### Retrieve customer's cooling-off period [GET]

+ Parameters

    + customerId (string)

+ Request

    + Headers
         
            Content-Type: application/json
            Authorization: {token}  

+ Response 200

    + Body
    
            {
              "coolingOffPeriodInHours": 24
            }

+ Response 401

+ Response 404

+ Response 500

## License's cooling-off period [/licenses/{licenseId}/cooling-off-period]